import localFont from "next/font/local";
import "./globals.css";
import Navbar from './_components/navbar/page';
import {Readex_Pro} from 'next/font/google'
import Footer from "./_components/footer/page";

const readex_pro = Readex_Pro({
  subsets:["arabic"]
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Tajwal Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning dir="rtl" className={readex_pro.className}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
